export const categories = [
  {
    category: 'Software Development',
    roles: [
      'Frontend Developer',
      'Backend Developer',
      'Full Stack Developer',
      'Mobile App Developer',
      'Desktop Application Developer',
      'Web Developer',
      'DevOps Engineer',
      'Software Engineer',
      'Embedded Systems Developer',
      'Firmware Developer',
    ],
  },
  {
    category: 'Database',
    roles: [
      'Database Administrator (DBA)',
      'Data Analyst',
      'Data Architect',
      'Big Data Engineer',
    ],
  },
  {
    category: 'UI/UX & Design',
    roles: [
      'UI/UX Designer',
      'UI Developer',
      'UX Researcher',
      'Interaction Designer',
    ],
  },
  {
    category: 'Testing & QA',
    roles: [
      'QA Engineer',
      'Test Automation Engineer',
      'Manual Tester',
      'Performance Tester',
      'Security Tester',
    ],
  },
  {
    category: 'Software Management & Architecture',
    roles: [
      'Software Architect',
      'Technical Lead',
      'Product Manager',
      'Project Manager',
      'Scrum Master',
    ],
  },
  {
    category: 'Specialized Software',
    roles: [
      'Data Scientist',
      'Machine Learning Engineer',
      'Artificial Intelligence Engineer',
      'Data Engineer',
      'Cloud Engineer',
      'Blockchain Developer',
      'Computer Vision Engineer',
      'AR/VR Developer',
      'Game Developer',
    ],
  },
  {
    category: 'System & Network',
    roles: [
      'System Administrator',
      'Network Engineer',
      'Site Reliability Engineer (SRE)',
      'IT Support Specialist',
    ],
  },
  {
    category: 'Cybersecurity',
    roles: [
      'Cybersecurity Analyst',
      'Security Engineer',
      'Penetration Tester',
      'Network Security Engineer',
      'Incident Response Analyst',
    ],
  },

  {
    category: 'Emerging Tech',
    roles: [
      'IoT Developer',
      'Quantum Computing Developer',
      'Robotics Engineer',
    ],
  },
  {
    category: 'Other Tech',
    roles: [
      'Technical Writer',
      'API Developer',
      'Research and Development (R&D) Engineer',
      'IT Consultant',
    ],
  },
];

export const jobsData = [
  {
    id: 1,
    company: {
      name: 'Tech Innovators',
      logo_url: '/logos/tech-innovators.png',
    },
    city: 'San Francisco',
    country: 'USA',
    created_at: '2024-09-10',
    currency: 'USD',
    description:
      'Lead software engineering team in building scalable web applications.',
    job_type: 'Full-time',
    level: 'Senior',
    salary: 120000,
    title: 'Software Engineer',
    work_mode: 'Remote',
  },
  {
    id: 2,
    company: {
      name: 'Digital Solutions',
      logo_url: '/logos/digital-solutions.png',
    },
    city: 'Berlin',
    country: 'Germany',
    created_at: '2024-08-25',
    currency: 'EUR',
    description: 'Develop and maintain complex frontend systems.',
    job_type: 'Contract',
    level: 'Mid',
    salary: 80000,
    title: 'Frontend Developer',
    work_mode: 'Onsite',
  },
  {
    id: 3,
    company: { name: 'FinTech Co.', logo_url: '/logos/fintech-co.png' },
    city: 'New York',
    country: 'USA',
    created_at: '2024-09-15',
    currency: 'USD',
    description:
      'Design financial algorithms and APIs for our next-gen platform.',
    job_type: 'Full-time',
    level: 'Junior',
    salary: 95000,
    title: 'Backend Developer',
    work_mode: 'Hybrid',
  },
  {
    id: 4,
    company: { name: 'Creative Labs', logo_url: '/logos/creative-labs.png' },
    city: 'Tokyo',
    country: 'Japan',
    created_at: '2024-08-05',
    currency: 'JPY',
    description:
      'Collaborate with cross-functional teams to design intuitive interfaces.',
    job_type: 'Full-time',
    level: 'Senior',
    salary: 10000000,
    title: 'UI/UX Designer',
    work_mode: 'Remote',
  },
  {
    id: 5,
    company: { name: 'AI Pioneers', logo_url: '/logos/ai-pioneers.png' },
    city: 'London',
    country: 'UK',
    created_at: '2024-09-02',
    currency: 'GBP',
    description: 'Develop and optimize AI models for real-world applications.',
    job_type: 'Part-time',
    level: 'Mid',
    salary: 65000,
    title: 'Machine Learning Engineer',
    work_mode: 'Onsite',
  },
  {
    id: 6,
    company: {
      name: 'Green Energy Solutions',
      logo_url: '/logos/green-energy.png',
    },
    city: 'Sydney',
    country: 'Australia',
    created_at: '2024-09-01',
    currency: 'AUD',
    description: 'Support development of renewable energy technologies.',
    job_type: 'Full-time',
    level: 'Mid',
    salary: 90000,
    title: 'Electrical Engineer',
    work_mode: 'Hybrid',
  },
  {
    id: 7,
    company: {
      name: 'E-Commerce Giants',
      logo_url: '/logos/e-commerce-giants.png',
    },
    city: 'Paris',
    country: 'France',
    created_at: '2024-07-30',
    currency: 'EUR',
    description: 'Lead the development of high-volume e-commerce platforms.',
    job_type: 'Full-time',
    level: 'Senior',
    salary: 110000,
    title: 'DevOps Engineer',
    work_mode: 'Remote',
  },
  {
    id: 8,
    company: { name: 'Tech Pro', logo_url: '/logos/tech-pro.png' },
    city: 'Dubai',
    country: 'UAE',
    created_at: '2024-08-18',
    currency: 'AED',
    description: 'Build modern web applications using React and Node.js.',
    job_type: 'Contract',
    level: 'Junior',
    salary: 70000,
    title: 'Full Stack Developer',
    work_mode: 'Onsite',
  },
  {
    id: 9,
    company: { name: 'Mobile Masters', logo_url: '/logos/mobile-masters.png' },
    city: 'Bangalore',
    country: 'India',
    created_at: '2024-09-10',
    currency: 'INR',
    description: 'Develop mobile apps with high performance and UX design.',
    job_type: 'Full-time',
    level: 'Mid',
    salary: 1200000,
    title: 'Mobile App Developer',
    work_mode: 'Hybrid',
  },
  {
    id: 10,
    company: { name: 'Data Experts', logo_url: '/logos/data-experts.png' },
    city: 'Toronto',
    country: 'Canada',
    created_at: '2024-08-28',
    currency: 'CAD',
    description:
      'Work with large data sets to provide insights for business decisions.',
    job_type: 'Full-time',
    level: 'Senior',
    salary: 95000,
    title: 'Data Analyst',
    work_mode: 'Remote',
  },
  {
    id: 11,
    company: {
      name: 'Cyber Security Corp',
      logo_url: '/logos/cyber-security.png',
    },
    city: 'Singapore',
    country: 'Singapore',
    created_at: '2024-09-05',
    currency: 'SGD',
    description: 'Protect systems and data from cyber threats and attacks.',
    job_type: 'Part-time',
    level: 'Mid',
    salary: 80000,
    title: 'Cyber Security Specialist',
    work_mode: 'Onsite',
  },
  {
    id: 12,
    company: {
      name: 'Blockchain Innovators',
      logo_url: '/logos/blockchain-innovators.png',
    },
    city: 'Zurich',
    country: 'Switzerland',
    created_at: '2024-09-07',
    currency: 'CHF',
    description: 'Build blockchain solutions for financial institutions.',
    job_type: 'Contract',
    level: 'Junior',
    salary: 75000,
    title: 'Blockchain Developer',
    work_mode: 'Remote',
  },
  {
    id: 13,
    company: {
      name: 'Healthcare Solutions',
      logo_url: '/logos/healthcare-solutions.png',
    },
    city: 'Stockholm',
    country: 'Sweden',
    created_at: '2024-09-03',
    currency: 'SEK',
    description: 'Develop software tools to support healthcare operations.',
    job_type: 'Full-time',
    level: 'Mid',
    salary: 85000,
    title: 'Healthcare Software Engineer',
    work_mode: 'Onsite',
  },
  {
    id: 14,
    company: { name: 'CloudNet', logo_url: '/logos/cloudnet.png' },
    city: 'Amsterdam',
    country: 'Netherlands',
    created_at: '2024-09-12',
    currency: 'EUR',
    description:
      'Architect and manage cloud infrastructure for large-scale applications.',
    job_type: 'Full-time',
    level: 'Senior',
    salary: 115000,
    title: 'Cloud Architect',
    work_mode: 'Hybrid',
  },
];
